import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  buttonsContainers: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },

  buttonContainer: {
    borderColor: "black",
    borderWidth: 3,
    borderRadius: 20,
    margin: 30,
    marginTop: 20,
    padding: 10,
    backgroundOpacity: 0.1,
    backgroundColor: "white",
    alignContent: "center",
    justifyContent: "center",
    flexDirection: "column",
  },
  headerText: {
    marginTop: height / 4,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 2,
  },
  idContainer: { flexDirection: "row", margin: 10 },
  singleContainer: {
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
  },
  container: {
    flex: 0.7,
    backgroundColor: "white",
  },
  header: {
    fontSize: 19,
    textAlign: "center",
    color: "white",
  },
  inputContainer: {
    marginRight: 18,
    borderRadius: 16,
    padding: 12,
    marginLeft: 18,
    backgroundColor: "white",
    marginBottom: 20,
    marginTop: 20,
  },
  item: {
    flex: 1,
    height: 60,
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "#1F51FF",

    borderWidth: 1,
    borderColor: "white",
    marginBottom: -1,
    justifyContent: "space-between",
  },
  items: {
    flex: 1,
    height: 10,
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "grey",

    borderWidth: 1,
    borderColor: "white",
    marginBottom: -1,
    justifyContent: "space-between",
  },
  inviteContainer: {
    flex: 0.5,
    height: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "grey",
    marginBottom: -1,
    justifyContent: "space-between",
    borderColor: "white",
    borderWidth: 1,
  },
  buttonContainer: {
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },
  button: {
    flexDirection: "row",
    margin: 30,
    padding: 25,
    paddingTop: 10,
    paddingBottom: 10,

    backgroundColor: "#1F51FF",
    borderRadius: 16,
    shadowOpacity: 0.8,
    shadowRadius: 16,
    shadowColor: "#1F51FF",
    justifyContent: "center",
    textAlign: "center",
  },
  container: {
    flex: 1,
  },
  container1: {
    alignContent: "center",
    justifyContent: "center",
    flex: 1,
  },
  spacer: {
    flex: 1,
    padding: 50,
  },
  counterContainer: {
    paddingBottom: 20,
    flexDirection: "row",
  },
  counterItemContainer: {
    flex: 1,
    alignItems: "center",
  },
  emailText: {
    padding: 20,
  },
  counterNumberText: {
    fontWeight: "bold",
    fontSize: 16,
  },
  flatList: {
    flex: 1,
    flexDirection: "column",
  },
  counterLabelText: {
    color: "gray",
    fontSize: 11,
  },
  grayOutlinedButton: {
    borderColor: "lightgray",
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 30,
    flex: 1,

    marginTop: 100,
  },
  grayOutlinedIconButton: {
    borderColor: "lightgray",
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginHorizontal: 10,
    flex: 1,
    paddingTop: 100,
  },
  filledButton: {
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 50,
    backgroundColor: "#ff4040",
  },
  filledButtonText: {
    color: "white",
    fontWeight: "700",
  },
  circleButtonContainer: {
    flexDirection: "row",
    marginRight: 18,
    marginLeft: 18,
    padding: 20,
    backgroundColor: "#1F51FF",
    borderRadius: 16,
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowColor: "#1F51FF",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 20,
  },
  subHeader: {
    fontSize: 12,
    color: "white",
  },
  dubHeader: {
    justifyContent: "center",
    alignContent: "center",
    textAlign: "center",
    fontSize: 14,
    color: "white",
  },

  flatListButtonContainer: {
    flexDirection: "column",
    marginTop: 50,
    marginRight: 18,
    marginLeft: 18,
    padding: 20,
    backgroundColor: "#1F51FF",
    borderRadius: 16,
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowColor: "#1F51FF",
    justifyContent: "center",
    textAlign: "center",
  },
  grayOutlinedButtonText: {
    color: "black",
    fontWeight: "700",
  },
  circleText: {
    fontSize: 19,
    color: "white",
  },
  app: {},
  toggle: {
    width: 100,
    height: 30,
    backgroundColor: "blue",
    justifyContent: "center",
    alignItems: "center",
  },
  toggleText: {
    color: "#fff",
  },
  boggle: {
    padding: 10,
  },
});

export default styles;
